export const ROLES = {
  ADMIN: "ADMIN",
  RECRUITER: "RECRUITER",
  INTERVIEWER: "INTERVIEWER",
  CANDIDATE: "CANDIDATE",
};

export const APPLICATION_STATUS = {
  APPLIED: "APPLIED",
  SCREENED: "SCREENED",
  TEST_SENT: "TEST_SENT",
  INTERVIEW: "INTERVIEW",
  OFFER: "OFFER",
  HIRED: "HIRED",
  REJECTED: "REJECTED",
};
